services:
  service-1:
    build:
      context: ./service-1
      dockerfile: Dockerfile
    depends_on:
      service-2:
        condition: service_started
    ports:
      - "8199:8080"

  service-2:
    build:
      context: ./service-2
      dockerfile: Dockerfile
