services:
  service-1:
    build:
      context: ./service-1
      dockerfile: Dockerfile
    ports:
      - "8199:8080"

  service-2:
    build:
      context: ./service-2
      dockerfile: Dockerfile
    ports:
      - "8081"
